command: ['streamlit', 'run', 'enhanced_healthcare_payor_app_mcp.py']
env:
  - name: 'DATABRICKS_WAREHOUSE_ID'
    valueFrom: "sql-warehouse"
  - name: 'STREAMLIT_GATHER_USAGE_STATS'
    value: 'false'
