# Healthcare Payor AI System Configuration
# Generated by start_healthcare_app.py

# Databricks Configuration
CATALOG = "my_catalog"
SCHEMA = "payer_silver"
DATABRICKS_PROFILE = "DEFAULT_azure"

# LLM Configuration
LLM_ENDPOINT = "databricks-meta-llama-3-3-70b-instruct"
LLM_TEMPERATURE = 0.1

# Debug Configuration
DEBUG = false
